version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angularjs"
  ]
  environment = [
    "nodejs",
    "vitest"
  ]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"